"""Pick the game's most valuable items, for the containers the console places.

    python tools/gen_loot.py --top 100
    python tools/gen_loot.py --top 100 --write

KOTOR 2 has a great many maps and very little worth finding in them. The point
of this list is that a crate placed from the console is worth opening: the
game's own containers stay exactly as they are, and only ours draw from here.

What goes in: every .uti blueprint in the BIFs and in the module archives,
ranked by Cost + AddCost. What stays out:

  - plot items. A quest object appearing in a random crate is at best confusing
    and at worst breaks the quest that expects to hand it to you.
  - items with no name in dialog.tlk, which are placeholders and test entries.
  - credits and stackables priced per unit, which would flood the list.

The output is a NWScript array compiled into k2se_spawn.nss, because the script
runs inside the engine and cannot read a CSV.
"""

import argparse
import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import gen_catalog as catalog  # noqa: E402
import kotor_res  # noqa: E402

RES_UTI = 2025

# Base item rows that are never interesting as random loot.
SKIP_BASEITEMS = {
    56,   # credits
}

SKIP_NAME_HINTS = ("test", "placeholder", "debug", "temp", "dummy")


def collect(game):
    kotor_res.GAME = game
    bifs, entries = kotor_res.read_key(os.path.join(game, "chitin.key"))
    tlk = catalog.TalkTable(os.path.join(game, "dialog.tlk"))

    seen = {}

    def add(resref, blob, source):
        key = resref.lower()
        if key in seen:
            return
        fields = catalog.gff_top_fields(blob)
        if not fields:
            return
        if fields.get("Plot", 0):
            return
        base = fields.get("BaseItem", -1)
        if isinstance(base, int) and base in SKIP_BASEITEMS:
            return
        cost = fields.get("Cost", 0)
        add_cost = fields.get("AddCost", 0)
        if not isinstance(cost, int):
            cost = 0
        if not isinstance(add_cost, int):
            add_cost = 0
        total = cost + add_cost
        if total <= 0:
            return
        name = ""
        loc = fields.get("LocalizedName")
        if isinstance(loc, tuple) and loc[0] == "strref":
            name = tlk.get(loc[1])
        # The shipped strings carry an internal tier marker -- "{30}Nomi's Robe",
        # "{light 15}Ulic Qel Droma's Mesh Suit". It is designer bookkeeping, not
        # part of the name a player should ever read.
        name = re.sub(r"^\{[^}]*\}\s*", "", name).strip()
        if not name:
            return
        low = name.lower()
        if any(hint in low for hint in SKIP_NAME_HINTS):
            return
        seen[key] = (resref, name, total, base if isinstance(base, int) else -1, source)

    for resref, restype, _bif, _idx in entries:
        if restype == RES_UTI:
            blob = kotor_res.extract(bifs, entries, resref, RES_UTI)
            if blob:
                add(resref, blob, "bif")

    modules = os.path.join(game, "modules")
    if os.path.isdir(modules):
        for filename in sorted(os.listdir(modules)):
            path = os.path.join(modules, filename)
            found = catalog.archive_entries(path)
            if not found:
                continue
            data = None
            for resref, restype, offset, size in found:
                if restype != RES_UTI or resref.lower() in seen:
                    continue
                if data is None:
                    with open(path, "rb") as fh:
                        data = fh.read()
                add(resref, data[offset:offset + size], os.path.splitext(filename)[0])

    items = list(seen.values())
    items.sort(key=lambda r: (-r[2], r[0]))
    return items


def render_nss(items):
    """The list as NWScript. A switch is used rather than a global array because
    the compiler this project ships does not take array initialisers."""
    lines = []
    lines.append("// GENERATED by tools/gen_loot.py -- do not edit by hand.")
    lines.append("// The %d most valuable non-plot items in the game." % len(items))
    lines.append("// Only containers placed by the K2SE console draw from this;")
    lines.append("// the game's own containers are untouched.")
    lines.append("int K2SE_LOOT_COUNT = %d;" % len(items))
    lines.append("")
    lines.append("string K2SE_LootItem(int n) {")
    lines.append("    switch (n) {")
    for i, (resref, name, value, _base, _source) in enumerate(items):
        safe = name.replace('"', "'")
        lines.append('        case %d: return "%s";   // %s, %d cr' % (i, resref, safe, value))
    lines.append('        default: break;')
    lines.append("    }")
    lines.append('    return "";')
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--game", default=kotor_res.GAME)
    ap.add_argument("--top", type=int, default=100)
    ap.add_argument("--write", action="store_true",
                    help="write nss/k2se_loot.nss for the spawn script")
    args = ap.parse_args()

    items = collect(args.game)
    top = items[:args.top]
    print("%d named, non-plot, priced items found; top %d:" % (len(items), len(top)))
    for i, (resref, name, value, base, source) in enumerate(top[:40]):
        print("  %3d %-18s %-42.42s %7d cr  base %-3d %s" % (i + 1, resref, name, value,
                                                             base, source))
    if len(top) > 40:
        print("  ... and %d more" % (len(top) - 40))

    if args.write:
        out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                           "nss", "k2se_loot.nss")
        with open(out, "w", encoding="ascii", errors="replace", newline="\n") as fh:
            fh.write(render_nss(top))
        print("\nwrote %s (%d items)" % (out, len(top)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
