// GENERATED by tools/gen_loot.py -- do not edit by hand.
// The 100 most valuable non-plot items in the game.
// Only containers placed by the K2SE console draw from this;
// the game's own containers are untouched.
int K2SE_LOOT_COUNT = 100;

string K2SE_LootItem(int n) {
    switch (n) {
        case 0: return "a_helmet_30";   // Force Focusing Visor, 62000 cr
        case 1: return "e_imp3_10";   // Mental Boost System, 61000 cr
        case 2: return "a_helmet_29";   // Absorption Visor, 60500 cr
        case 3: return "a_light_15";   // Ulic Qel Droma's Mesh Suit, 60000 cr
        case 4: return "a_medium_15";   // Jamoh Hogra's Battle Armor, 60000 cr
        case 5: return "a_robe_30";   // Nomi's Robe, 60000 cr
        case 6: return "d_tool_15";   // Droid Micro-Optics, 60000 cr
        case 7: return "e_imp2_10";   // Mental Boost Implant, 60000 cr
        case 8: return "w_brifle_30";   // Zersium Rifle, 60000 cr
        case 9: return "w_melee_30";   // Freyyr's Warblade, 59910 cr
        case 10: return "d_armor_15";   // Droid Energized Armor Mark III, 59810 cr
        case 11: return "a_gloves_30";   // Lightning Gloves, 59200 cr
        case 12: return "e_imp1_10";   // Mental Boost Package, 59000 cr
        case 13: return "a_belt_30";   // Jal Shey Mentor Belt, 58000 cr
        case 14: return "e_imp4_10";   // Mental Boost D-Package, 58000 cr
        case 15: return "w_blaste_30";   // Freedon Nadd's Blaster, 58000 cr
        case 16: return "d_interface_15";   // Droid Systems Upgrade, 57760 cr
        case 17: return "a_light_14";   // Zabrak Field Armor, 57250 cr
        case 18: return "a_helmet_28";   // Force Shield, 56750 cr
        case 19: return "w_brifle_29";   // Verpine Droid Disintegrator, 56000 cr
        case 20: return "e_imp3_09";   // Physical Boost System, 55600 cr
        case 21: return "a_gloves_29";   // Improved Automation Gloves, 55000 cr
        case 22: return "a_heavy_14";   // Felenar Armor, 55000 cr
        case 23: return "a_heavy_15";   // Matrix Armor, 55000 cr
        case 24: return "e_imp2_09";   // Physical Boost Implant, 54600 cr
        case 25: return "a_belt_29";   // Aratech Echo Belt, 54400 cr
        case 26: return "a_robe_29";   // Crado's Robe, 54400 cr
        case 27: return "d_tool_14";   // Droid CEPB, 54400 cr
        case 28: return "w_blaste_29";   // Dashade Sonic Disruptor, 54400 cr
        case 29: return "w_melee_29";   // Gand Discharger, 54000 cr
        case 30: return "w_blaste_28";   // Mandalorian Disintegrator, 53900 cr
        case 31: return "e_imp1_09";   // Physical Boost Package, 53600 cr
        case 32: return "d_armor_14";   // Droid Energized Armor Mark II, 53300 cr
        case 33: return "a_gloves_28";   // Disruption Gloves, 52000 cr
        case 34: return "w_brifle_28";   // Mandalorian Heavy Repeater, 51900 cr
        case 35: return "a_medium_14";   // Electromesh Armor, 51000 cr
        case 36: return "a_belt_28";   // Immortality Belt, 50800 cr
        case 37: return "a_robe_28";   // Thon's Robe, 50800 cr
        case 38: return "a_helmet_25";   // Circlet of Saresh, 50250 cr
        case 39: return "a_gloves_27";   // Ossluk's Gloves, 50000 cr
        case 40: return "a_robe_26";   // Darth Malak's Armor, 50000 cr
        case 41: return "d_interface_14";   // Droid Source Ripper, 50000 cr
        case 42: return "g1_w_sbrcrstl21";   // + dual strike <CUSTOM0>, 50000 cr
        case 43: return "w_melee_28";   // Zhaboka, 50000 cr
        case 44: return "a_helmet_27";   // Enchanced Shielding Visor, 49500 cr
        case 45: return "w_brifle_27";   // Sonic Disruptor, 49500 cr
        case 46: return "e_imp2_08";   // Durability Implant, 49200 cr
        case 47: return "e_imp1_08";   // Health Package, 48200 cr
        case 48: return "e_imp3_08";   // Numbness System, 47700 cr
        case 49: return "a_belt_27";   // Qel-Droma Belt, 47200 cr
        case 50: return "a_robe_27";   // Jolee's Robe, 47200 cr
        case 51: return "d_tool_13";   // Droid CESS, 47200 cr
        case 52: return "e_imp4_09";   // Physical Boost D-Package, 47200 cr
        case 53: return "w_blaste_27";   // Elite Watchman Blaster, 47200 cr
        case 54: return "w_melee_27";   // Tehk'la Blade, 46000 cr
        case 55: return "a_heavy_13";   // Iotran Braceman Armor, 45000 cr
        case 56: return "w_brifle_25";   // Slavemaster Stun Carbine, 45000 cr
        case 57: return "a_helmet_26";   // Bindo's Band, 44500 cr
        case 58: return "d_armor_13";   // Droid Energized Armor Mark I, 44500 cr
        case 59: return "a_medium_13";   // Verpine Fiber Ultramesh, 44000 cr
        case 60: return "a_gloves_26";   // Nikto Soldier Gloves, 43800 cr
        case 61: return "a_belt_26";   // GNS Strength Enhancer, 43600 cr
        case 62: return "w_blaste_26";   // Micro-Pulse Blaster, 43600 cr
        case 63: return "w_brifle_26";   // Onderon Repeating Carbine, 43550 cr
        case 64: return "a_light_13";   // Reinforced Fiber Armor, 43500 cr
        case 65: return "a_helmet_24";   // Target Assessor, 42250 cr
        case 66: return "w_melee_26";   // Geonosian Electro-Staff, 41900 cr
        case 67: return "a_helmet_23";   // Matukai Meditation Band, 41500 cr
        case 68: return "a_robe_25";   // Sylvar's Robe, 41500 cr
        case 69: return "u_r_firi_15";   // Mandalorian Chamber Mark III, 40150 cr
        case 70: return "a_belt_25";   // Aratech Cardio-Regulator, 40000 cr
        case 71: return "a_gloves_25";   // Dominator Gauntlets, 40000 cr
        case 72: return "a_heavy_12";   // M'uhk'gfa, 40000 cr
        case 73: return "d_interface_13";   // Droid Scavenger Upgrade, 40000 cr
        case 74: return "d_tool_12";   // Droid CERS, 40000 cr
        case 75: return "g1_w_sbrcrstl20";   // Door Cutting, 40000 cr
        case 76: return "w_blaste_25";   // Systech Electric Blaster, 40000 cr
        case 77: return "u_a_unde_30";   // Durasteel Underlay Mark V, 39950 cr
        case 78: return "u_l_cell_13";   // Ultimate Diatium Energy Cell, 39750 cr
        case 79: return "u_m_grip_15";   // Superior Nagai Grip, 39535 cr
        case 80: return "a_robe_24";   // Aleema Keto's Robe, 39000 cr
        case 81: return "u_r_targ_15";   // Targeting Scope Mark IV, 39000 cr
        case 82: return "u_m_cell_15";   // Enhanced Energy Cell Mark IV, 38750 cr
        case 83: return "u_a_unde_29";   // Flexible Underlay Mark V, 38450 cr
        case 84: return "u_a_over_30";   // Bonded Plates Mark IV, 38350 cr
        case 85: return "u_l_emit_13";   // Refined Phobium Emitter, 38285 cr
        case 86: return "a_light_12";   // Echani Shield Suit, 38250 cr
        case 87: return "u_r_powe_15";   // Pure Rylith Power Cell, 38165 cr
        case 88: return "a_helmet_21";   // Sith Mask, 38000 cr
        case 89: return "u_l_lens_13";   // Enhanced Byrothsis Lens, 38000 cr
        case 90: return "w_brifle_24";   // Zabrak Blaster Carbine, 37600 cr
        case 91: return "u_m_edge_15";   // Ostrine Edge, 37350 cr
        case 92: return "d_armor_12";   // Droid Diatium Plating, 37100 cr
        case 93: return "a_medium_12";   // Heavy Cinnagar War Suit, 37000 cr
        case 94: return "w_melee_25";   // Arg'garok, 37000 cr
        case 95: return "a_gloves_24";   // Zeison Sha Gloves, 36500 cr
        case 96: return "a_belt_24";   // Tech Specialist Belt, 36400 cr
        case 97: return "e_imp4_08";   // Universal D-Package, 36400 cr
        case 98: return "w_blaste_24";   // Zabrak Heavy Blaster, 36400 cr
        case 99: return "d_interface_12";   // Droid Anatomy Library, 36000 cr
        default: break;
    }
    return "";
}
