// K2SE spawner script. K2SE runs it (CVirtualMachine::RunScript) on the player a
// moment after every area setup and then every few seconds of gameplay. It asks
// K2SE for the spawn entries of the current module, finds the ones already in
// the area (every object it creates is stamped with LocalBoolean 150 and
// LocalNumber 25 = entry index, both saved with the area) and creates the
// missing ones with the engine's own CreateObject.
//
// Two things happen to what it creates, and neither happens to anything the
// game itself placed:
//
//   containers get loot. KOTOR 2 has a great many maps and very little worth
//   finding in them, so a crate placed from the console is worth opening: it is
//   filled from the hundred most valuable non-plot items in the game
//   (k2se_loot.nss, generated by tools/gen_loot.py). The game's own containers
//   are left exactly as they are.
//
//   creatures walk. A spawned NPC standing still forever reads as furniture, so
//   each one is given a wander loop -- it roams the walkmesh, pauses, and moves
//   on, which can carry it well away from where it was placed.
//
// Compiled against nwscript_k2se.nss (routines 898..907), deployed as
// override/k2se_spawn.ncs by tools/deploy_movement.py.

#include "k2se_loot"

int K2SE_SPAWN_FLAG = 150;   // LocalBoolean index: "created by K2SE"
int K2SE_SPAWN_INDEX = 25;   // LocalNumber index: entry number (1..255)
int K2SE_LOOTED_FLAG = 151;  // LocalBoolean index: "already filled with loot"

int K2SE_LOOT_MIN = 1;       // items per container
int K2SE_LOOT_MAX = 3;

// A crate the player never opens should not have cost anything, but the loot has
// to exist before it is opened, so it is created once at spawn time and marked.
void K2SE_FillContainer(object oBox)
{
    if (GetLocalBoolean(oBox, K2SE_LOOTED_FLAG)) return;
    SetLocalBoolean(oBox, K2SE_LOOTED_FLAG, TRUE);

    int nHowMany = K2SE_LOOT_MIN + Random(K2SE_LOOT_MAX - K2SE_LOOT_MIN + 1);
    int i;
    for (i = 0; i < nHowMany; i++)
    {
        string sItem = K2SE_LootItem(Random(K2SE_LOOT_COUNT));
        if (sItem != "") CreateItemOnObject(sItem, oBox, 1);
    }
}

// Wandering, without a heartbeat script of its own: the action queue is topped
// up whenever this pass finds the creature idle. Random walk follows the area's
// walkmesh, so the NPC keeps to floors and doors and can end up a long way from
// where it started.
void K2SE_KeepWandering(object oNPC)
{
    if (!GetIsObjectValid(oNPC)) return;
    if (GetCurrentAction(oNPC) != ACTION_INVALID) return;   // already busy
    if (GetIsInConversation(oNPC)) return;
    if (GetIsInCombat(oNPC)) return;

    AssignCommand(oNPC, ActionRandomWalk());
    // A pause every so often, so it looks like someone going somewhere rather
    // than a patrol robot.
    if (Random(3) == 0)
    {
        AssignCommand(oNPC, ActionWait(IntToFloat(2 + Random(6))));
    }
}

void main()
{
    object oPC = GetFirstPC();
    if (!GetIsObjectValid(oPC)) return;
    object oArea = GetArea(oPC);
    if (!GetIsObjectValid(oArea)) return;

    int nCount = K2SE_SpawnBegin(GetModuleName(), GetTag(oArea));
    if (nCount <= 0) return;

    int nFilter = OBJECT_TYPE_PLACEABLE | OBJECT_TYPE_CREATURE;
    object o = GetFirstObjectInArea(oArea, nFilter);
    while (GetIsObjectValid(o))
    {
        if (GetLocalBoolean(o, K2SE_SPAWN_FLAG))
        {
            K2SE_SpawnMarkPresent(GetLocalNumber(o, K2SE_SPAWN_INDEX));
            // Ours, and already in the world: keep it moving if it is a creature.
            if (GetObjectType(o) == OBJECT_TYPE_CREATURE) K2SE_KeepWandering(o);
        }
        o = GetNextObjectInArea(oArea, nFilter);
    }

    int i;
    for (i = 1; i <= nCount; i++)
    {
        if (K2SE_SpawnNeeded(i))
        {
            vector vPos = Vector(K2SE_SpawnX(i), K2SE_SpawnY(i), K2SE_SpawnZ(i));
            location lLoc = Location(vPos, K2SE_SpawnFacing(i));
            int nType = K2SE_SpawnType(i);
            object oNew = CreateObject(nType, K2SE_SpawnTemplate(i), lLoc, FALSE);
            if (GetIsObjectValid(oNew))
            {
                SetLocalBoolean(oNew, K2SE_SPAWN_FLAG, TRUE);
                SetLocalNumber(oNew, K2SE_SPAWN_INDEX, i);
                if (nType == OBJECT_TYPE_PLACEABLE)
                {
                    // Only containers can hold anything; asking a statue to take
                    // an item silently does nothing, so check first.
                    if (GetHasInventory(oNew)) K2SE_FillContainer(oNew);
                }
                else if (nType == OBJECT_TYPE_CREATURE)
                {
                    K2SE_KeepWandering(oNew);
                }
                K2SE_SpawnReport(i, TRUE);
            }
            else
            {
                K2SE_SpawnReport(i, FALSE);
            }
        }
    }
}
